### ISSUE TITLE
dev importation of d3-scale and react

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/iv-spectrum#28]
I don't find it normal that we need to import types for d3 and react while we are not using it in this project.

There should be a better way to that it is present only in common-spectrum.

    "@types/d3-scale": "^3.2.2",
    "@types/jest": "^26.0.20",
    "@types/react": "^17.0.2"

**Comment by maasencioh** [comment]
`@types/jest` is used in this project, the other ones we can add only to common-spectrum indeed.
