### ISSUE TITLE
Missing reexport from common-spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/iv-spectrum#29]
@maasencioh you removed those reexport from common-spectrum during the refactoring and change the testcase 'fromJcamp'.

What is the reason for this because this is a breaking change and we can not build the package for the browser anymore in which we need the fromJcamp and toJcamp methods.

```
export {
  Analysis,
  AnalysesManager,
  fromJcamp,
  toJcamp,
  JSGraph,
} from 'common-spectrum'
```

**Comment by maasencioh** [comment]
I was not aware that this needed to be also exported to lactame or something like this, that's why I deleted the unused exporting methods.

What is the change of the 'fromJcamp' that you want me to review?
